# Numpy

https://numpy.org/

## What is it? 
- Numpy is a Python library used for working with arrays
- Numpy is the fundamental package for scientific computing in Python


## Why do we care? 
- Numpy is one of the main reasons why Python is so powerful and popular for scientific computing
- Super fast. Numpy arrays are implemented in C, which makes numpy very fast.
- The arrays allows for vectorized operations

## Show us! 

### Create a 1D array

#### create a list
format: list()

In [73]:
#create a list
my_list = [1, 2, 3, 4]
my_list

[1, 2, 3, 4]

In [2]:
#whats the type
type(my_list)

list

In [4]:
#what is dtype

AttributeError: 'list' object has no attribute 'dtype'

In [8]:
#whats the shape
my_list.shape

AttributeError: 'list' object has no attribute 'shape'

#### create an array
format: np.array()

In [5]:
#import numpy
import numpy as np

In [10]:
#create the array
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4])

In [11]:
#whats the type
type(my_array)

numpy.ndarray

In [12]:
#whats the shape
my_array.shape

(4,)

In [13]:
my_array.dtype

dtype('int64')

#### access elements of our new array

In [14]:
my_array[0]

1

In [15]:
my_array[-1]

4

In [16]:
my_array

array([1, 2, 3, 4])

#### slice the array

In [17]:
my_array[1:]

array([2, 3, 4])

In [ ]:
my_array[:2]

In [19]:
my_array[0:4]

array([1, 2, 3, 4])

#### create an array from 1 to 100

In [22]:
#np.array(?)
a = np.array(range(1,101))
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
#access single element
a[0]

1

In [25]:
#slice the array! 
a[-1]

100

In [26]:
a[25:]

array([ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [27]:
a[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

### Create a 2D array

In [35]:
#build a list of lists
matrix = [[1,2,3],
[2,3,4],
[6,7,8],
[5,6,7]]
matrix

[[1, 2, 3], [2, 3, 4], [6, 7, 8], [5, 6, 7]]

In [31]:
type(matrix)

list

In [36]:
#turn it into an array! 
matrix_array = np.array(matrix)
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [5, 6, 7]])

In [33]:
#type
type(matrix_array)

numpy.ndarray

In [37]:
matrix_array.shape

(4, 3)

In [38]:
matrix_array.dtype

dtype('int64')

#### access elements

In [39]:
matrix_array

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8],
       [5, 6, 7]])

In [40]:
matrix_array[0]

array([1, 2, 3])

In [41]:
matrix_array[0,0]

1

In [42]:
matrix_array[2,1]

7

### Descriptive Stats

In [43]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

#### using methods: the method is called on the numpy object

In [45]:
a.min()

1

In [46]:
a.max()

100

In [47]:
a.std(), a.mean()

(28.86607004772212, 50.5)

In [48]:
a.sum()

5050

#### using functions: using numpy to call functions

In [50]:
np.max(a)

100

In [214]:
np.std(a)

28.86607004772212

In [215]:
np.mean(a)

50.5

In [216]:
np.sum(a)

5050

### Array of Booleans! 

### Boolean Masks

1. create an array
2. make a list of booleans (mask)
3. combine

    format: array [ list of booleans ] 

In [51]:
#pull back our small array
my_array

array([1, 2, 3, 4])

In [54]:
#make list of booleans aka our mask
mask = [True, False, False, True]
mask

[True, False, False, True]

In [55]:
#combine them 
my_array[mask]

array([1, 4])

#### how else can we get our array of boolean values?

In [56]:
my_array

array([1, 2, 3, 4])

In [58]:
#write a conditional with the array
my_array == 4


array([False, False, False,  True])

In [60]:
mask = (my_array == 4)

In [61]:
my_array[mask]

array([4])

In [64]:
mask = my_array > 2
mask

array([False, False,  True,  True])

In [65]:
my_array[mask]

array([3, 4])

#### make and apply our boolean mask

array([False, False, False,  True, False])

In [485]:
#format: array_name [ list_of_booleans ]


In [68]:
mask = (my_array == 2) | (my_array == 4)
mask

array([False,  True, False,  True])

In [69]:
my_array[mask]

array([2, 4])

#### cool! can we just do it with a list instead of an array?

In [70]:
#pull back our initial list
my_list

[1, 2, 3, 4]

In [75]:
#create a array of booleans
my_list == 4

False

In [76]:
#apply an array of booleans to a list
mask

array([False,  True, False,  True])

In [77]:
my_list[mask]

TypeError: only integer scalar arrays can be converted to a scalar index

#### let's bring it back to arrays and make them bigger

In [78]:
#array
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [85]:
#mask
mask = a >= 90
mask

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [86]:
#boolean mask
a[mask]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

#### shortcut?

In [88]:
a[a >= 90]

array([ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [89]:
a[a==4]

array([4])

#### what if we wanted to check two conditions?

In [94]:
# note the parenthesis
# also note that we're using & instead of and
mask = (a > 5) & (a < 15)

In [95]:
a[mask]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14])

#### what if we wanted the opposite of our mask?

In [96]:
~mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [493]:
# the ~ notates the opposite of


In [98]:

list(matrix_array)

[array([1, 2, 3]), array([2, 3, 4]), array([6, 7, 8]), array([5, 6, 7])]

## Vectorization Operations
- makes looping over math so easy and fast!

### Add one to every element

#### hard way: doing it in a list

In [100]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [101]:
#using a for loop
new_list = []
for x in my_list:
    print(x+1)
    new_list.append(x+1)
new_list

2
3
4
5


[2, 3, 4, 5]

In [102]:
#using a list comprehension
[x+1 for x in my_list]

[2, 3, 4, 5]

#### easy way: doing it with an array

In [103]:
my_array

array([1, 2, 3, 4])

In [104]:
#using vectorization operations
my_array + 1

array([2, 3, 4, 5])

### more operations

In [105]:
my_array * 2

array([2, 4, 6, 8])

In [106]:
my_array ** 2

array([ 1,  4,  9, 16])

In [107]:
my_array/10

array([0.1, 0.2, 0.3, 0.4])

In [108]:
my_array/10 + 2

array([2.1, 2.2, 2.3, 2.4])

In [109]:
np.log(my_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

### show us the speed

In [111]:
#make a really big array
big_array = np.array(range(1_000_001))
big_array

array([      0,       1,       2, ...,  999998,  999999, 1000000])

In [120]:
%%timeit

big_array ** 2

372 µs ± 97.7 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [116]:
#make a really big list
big_list = list(big_array)
big_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [125]:
%%timeit

for x in big_list:
    x**2

166 ms ± 997 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Numpy ways to create arrays

#### full of zeros

In [130]:
np.zeros((10,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.zeros()

#### full of ones

In [127]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### full of whatever you want 

In [131]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [132]:
np.full((10,2),3)

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

#### a quicker way to make a range

In [133]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [134]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### an array of random integers

In [218]:
#np.random.randint()
np.random.randint(1,3,10)

array([1, 2, 2, 2, 1, 1, 1, 2, 2, 1])

#### an array of random numbers from the standard distribution

In [219]:
#np.random.randn()
np.random.randn(10)

array([-1.64341675, -0.17003995, -1.24736516,  1.80709696,  0.62549263,
       -0.16264038,  0.55338167, -0.80124175,  0.68933955, -0.3106143 ])

In [222]:
np.random.randn(100000000).mean()

0.00013150629691659782